# SPDX-FileCopyrightText: 2024 Nicco Kunzmann and Open Web Calendar Contributors <https://open-web-calendar.quelltext.eu/>
#
# SPDX-License-Identifier: CC-BY-SA-4.0

authors:
  niccokunzmann:
    name: Nicco Kunzmann
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/564768?v=4
