# Run pytest for each commit.
# See also
#    https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#running-tests-with-tox
name: Test with pytest and tox

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        tox_env: ["py"]
        # see https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#expanding-or-adding-matrix-configurations
        include:
        # run Firefox
        - python: "3.9"
          tox_env: web
        # run Chrome
        - python: "3.9"
          tox_env: "web -- -D browser=chrome"
        # run Firefox in iPhone 11 responsive layout
        - python: "3.9"
          tox_env: "web -- -D window=375x812"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install test packages
        run: pip install tox
      - name: Run tests
        # Run tox using the version of Python in `PATH`
        run: tox -e ${{ matrix.tox_env }}

  gh-pages:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for mkdocs git date, see  https://github.com/timvink/mkdocs-git-revision-date-localized-plugin?tab=readme-ov-file#note-when-using-build-environments
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12
      - name: Install test packages
        run: pip install tox
      - name: mkdocs
        # Run tox using the version of Python in `PATH`
        run: tox -e docs -- gh-deploy
